-- =============================================================
-- God Cares Ministries - Supabase Schema
-- Run this in the Supabase SQL Editor to create the tables
-- and enable anonymous (public) INSERTs from the website forms.
-- =============================================================

-- -------------------------------------------------------------
-- 1) DONATIONS / CONTRIBUTIONS table
--    Used by the "Donate Us" page form
-- -------------------------------------------------------------
create table if not exists public.donations (
    id           bigint generated by default as identity primary key,
    name         text not null,
    email        text,
    phone        text,
    amount       numeric(14, 2) not null,
    message      text,
    created_at   timestamptz not null default now()
);

alter table public.donations enable row level security;

-- Allow anyone to insert a donation (from the public donate form)
create policy "Allow public donations insert"
    on public.donations
    for insert
    with check (true);

-- Only authenticated/admins can read
create policy "Allow authenticated read donations"
    on public.donations
    for select
    using (auth.role() = 'authenticated');

-- -------------------------------------------------------------
-- 2) PARTICIPANTS table
--    Used by the Church "Participant Registration" page form
-- -------------------------------------------------------------
create table if not exists public.participants (
    id               bigint generated by default as identity primary key,
    full_name        text not null,
    spouse_name      text,
    age              text,
    dob              text,
    gender           text,
    whatsapp         text,
    email            text,
    occupation       text,
    location         text,
    govt_id          text,
    address          text,
    role             text,
    language         text,
    payment_id       text,
    payment_order_id text,
    razorpay_signature text,
    amount           numeric(14, 2) default 1000.00,
    payment_status   text not null default 'paid',
    created_at       timestamptz not null default now()
);

alter table public.participants enable row level security;

-- Allow anyone to register (from the public participant form)
create policy "Allow public participants insert"
    on public.participants
    for insert
    with check (true);

-- Only authenticated/admins can read
create policy "Allow authenticated read participants"
    on public.participants
    for select
    using (auth.role() = 'authenticated');

-- -------------------------------------------------------------
-- 3) Payment columns migration (run once if participants already exists)
-- -------------------------------------------------------------
alter table public.participants
    add column if not exists payment_id          text,
    add column if not exists payment_order_id    text,
    add column if not exists razorpay_signature  text,
    add column if not exists amount              numeric(14, 2) default 1000.00,
    add column if not exists payment_status      text not null default 'paid';